### ISSUE TITLE
Update JSON format

### ISSUE THREAD

**Issue by alessandrorecca** [nkdAgility/Azure-DevOps-WorkItem-Clone#44]
[tst_jsonj_export_v20 1.json](https://github.com/user-attachments/files/16156790/tst_jsonj_export_v20.1.json)

**Comment by MrHinsh** [comment]
Can we get a correction to:
```
{
  "id": 213928,
  "fields": {
    "System.AreaPath": "Engineering Group\\ECH Group\\ECH TPL 1",
    "System.Tags": "Customer Document",
    "System.Title": "Technical specification",
    "Custom.Product": "CC",
    "System.Effort": 12,
    "Custom.TRA_Milestone": "E0.1"
  }
},
```

**Comment by alessandrorecca** [comment]
Here is the updated JSON:

[tst_jsonj_export_v04.json](https://github.com/user-attachments/files/16164411/tst_jsonj_export_v04.json)
