### ISSUE TITLE
Auto generate query at the end (stage 7)

### ISSUE THREAD

**Issue by alessandrorecca** [nkdAgility/Azure-DevOps-WorkItem-Clone#52]
After creating the work items, the following Shared Query shall be generated:

```
SELECT
    [Custom.Product],
    [System.Title],
    [System.Description],
    [Custom.DeadlineDate],
    [System.AreaPath],
    [System.AssignedTo],
    [System.State],
    [Custom.Notes],
    [System.WorkItemType],
    [Custom.TRA_Milestone]
FROM workitemLinks
WHERE
    (
        [Source].[System.Id] = <<ADD "targetParentId" here, e. g. 257707>>
        OR [Source].[System.Parent] = <<ADD "targetParentId" here, e. g. 257707>>
        OR [Source].[System.Tags] CONTAINS 'xxxx xxxx'
    )
    AND (
        [System.Links.LinkType] = 'System.LinkTypes.Hierarchy-Forward'
    )
    AND (
        [Target].[System.Parent] = <<ADD "targetParentId" here, e. g. 257707>>
        OR [Target].[System.Tags] CONTAINS 'xxxx xxxx'
    )
ORDER BY [Custom.DeadlineDate]
MODE (Recursive)
```

Further details:
- The generated shared query shall be stored here:
![image](https://github.com/user-attachments/assets/65c2da57-0c6a-46e8-8b77-3277656a0754)

- The name of the shared query shall be the same as the title of "targetParentId"

- If some items could not be created and were skipped, the tool should ask the user whether the query shall still be created,

**Comment by MrHinsh** [comment]
thats a lot of OR!

I'm struggling to get it to create a query. I have an open asked for the Product Team. The docs suck...

**Comment by MrHinsh** [comment]
How do we know what Tag is?

**Comment by alessandrorecca** [comment]
Tag is not really required here, since we specify the targetParentID. You can just set it to 'xxxx xxxx'

**Comment by alessandrorecca** [comment]
so they could add something manual there if they want to do that in addition to the targetParentID

**Comment by MrHinsh** [comment]
First version is quite buggy. If the query is not right it will crash.
