### ISSUE TITLE
Cache Not Reloading Correctly After Multiple Changes to Template Work Items

### ISSUE THREAD

**Issue by alessandrorecca** [nkdAgility/Azure-DevOps-WorkItem-Clone#53]
We have identified a bug in the latest release where changes made to template work items do not consistently trigger a cache reload. This issue affects the accuracy of work items generated in the production systems.

Steps to Reproduce:

1. Make a change to a template work item.
2. Save the changes.
3. Observe that the cache is reloaded correctly after the first change.
4. Make another change to the same work item or to a different work item.
5. Save the changes.
6. Observe that the cache is not reloaded after the second change.

Expected Result:
The cache should be reloaded every time a change is made to any template work item to ensure that work items generated in the production systems are up-to-date.

Actual Result:
The cache is reloaded only after the first change to a template work item. Subsequent changes do not trigger a cache reload, leading to outdated content in the generated work items.

Impact:
Work items generated in the production systems are not up-to-date.

**Comment by MrHinsh** [comment]
Hmm, that's interesting as I am compiring the file write time...

Oh... did you complete step 4 while the 3 is rebuilding... that would mean that the file write time is after the work item edit time... I can fix that...

**Comment by alessandrorecca** [comment]
Nope. The pipeline was completely finished before I made the next change. If you want, I can also demonstrate you live whats going on if that helps.

**Comment by MrHinsh** [comment]
@alessandrorecca I've implemented a fix that might resolve it. I'm still interested in a demo... but maybe with the new version :)
